import type { Metadata } from "next";
import {
    Geist,
    Geist_Mono,
    Playfair_Display,
    Open_Sans,
} from "next/font/google";
import {} from "next/font/google";
import { AuthProvider } from "@/contexts/AuthContext";

import "./globals.css";
import Footer from "../components/landing/footer/Footer";
import Navbar from "../components/landing/header/Navbar";

const playfair = Playfair_Display({
    variable: "--font-playfair",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

const openSans = Open_Sans({
    variable: "--font-openSans",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={` ${openSans.variable} ${playfair.variable} antialiased`}
            >
                <AuthProvider>
                    <Navbar />
                    {children}
                    <Footer />
                </AuthProvider>
            </body>
        </html>
    );
}
